const USER_LOGIN_ERROR = 'USER_LOGIN_ERROR';
const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
const USER_LOGOUT = 'USER_LOGOUT';
const GET_ITEMS="GET_ITEMS"
const ADD_TO_CART="ADD_TO_CART"
const ADD_TO_CART_ERROR="ADD_TO_CART_ERROR"
const REMOVE_ITEM_FROM_CART="REMOVE_ITEM_FROM_CART"
const UPDATE_ITEM_FROM_CART="UPDATE_ITEM_FROM_CART"
const GET_CART="GET_CART"
const GET_CART_ERROR="GET_CART_ERROR"
const CHECKOUT_SUCCESS='CHECKOUT_SUCCESS'
const CHECKOUT_ERROR='CHECKOUT_ERROR'
const ORDERED_ITEMS='ORDERED_ITEMS'
const GET_FAVOURITE='GET_FAVOURITE'
const GET_FAVOURITE_ERROR='GET_FAVOURITE_ERROR'
const GET_PROFILE='GET_PROFILE'
const UPDATE_QUANTITY='UPDATE_QUANTITY'
module.exports={
    USER_LOGIN_ERROR,USER_LOGIN_SUCCESS,USER_LOGOUT,GET_ITEMS,ADD_TO_CART,ADD_TO_CART_ERROR,REMOVE_ITEM_FROM_CART,UPDATE_ITEM_FROM_CART,
    GET_CART,GET_CART_ERROR,CHECKOUT_SUCCESS,CHECKOUT_ERROR,ORDERED_ITEMS,GET_FAVOURITE,GET_FAVOURITE_ERROR,GET_PROFILE,UPDATE_QUANTITY
}

