const DASHBOARd_TOPIC="DASHBOARD_TOPIC";
const ADDFAVOURITE_TOPIC="addFavourite_topic";
const ADDITEM_TOPIC="AddItem_topic";
const ADDTOCART_TOPIC="addToCart_topic";
const CHECKOUT_TOPIC="checkOut_topic";
const GETITEMLISTFORDASHBOARD_TOPIC="getItemListForDashboard_topic";
const CREATESHOP_TOPIC="createShop_topic";
const GETCART_TOPIC="getCart_topic";
const GETCATEGORIES_TOPIC="getCategories_topic";
const GETITEM_TOPIC="getItem_topic";
const GETITEMDETAILS_TOPIC="getItemDetails_topic";
const GETITEMLISTBYSHOPID_TOPIC="getItemListbyShopID_topic";
const GETORDEREDITEMS_TOPIC="getOrderedItems_topic";
const GETPROFILE_TOPIC="getProfile_topic";
const GETSHOPDETAILS_TOPIC="getShopDetails_topic";
const GETSHOPDETAILSBYUSERID_TOPIC="getShopDetailsbyUserId_topic";
const GETSHOPNAME_TOPIC="getShopName_topic";
const PASSPORT_TOPIC="passport_topic";
const REGISTER_TOPIC="register_topic";
const REMOVEFAVOURITE_TOPIC="removeFavourite_topic";
const SUBMITPROFILE_TOPIC="submitProfile_topic";
const UPDATEITEM_TOPIC="updateItem_topic";
const UPDATESHOP_TOPIC="updateShop_topic";
module.exports={
    DASHBOARd_TOPIC,ADDFAVOURITE_TOPIC,UPDATEITEM_TOPIC,ADDITEM_TOPIC,ADDTOCART_TOPIC,CHECKOUT_TOPIC,GETITEMLISTFORDASHBOARD_TOPIC,CREATESHOP_TOPIC,GETCART_TOPIC,GETCATEGORIES_TOPIC,
    GETITEM_TOPIC,GETITEMDETAILS_TOPIC,GETITEMLISTBYSHOPID_TOPIC,GETORDEREDITEMS_TOPIC,GETPROFILE_TOPIC,GETSHOPDETAILS_TOPIC,GETSHOPDETAILSBYUSERID_TOPIC,
    GETSHOPNAME_TOPIC,PASSPORT_TOPIC,REGISTER_TOPIC,REMOVEFAVOURITE_TOPIC,SUBMITPROFILE_TOPIC,UPDATESHOP_TOPIC

}